### ISSUE TITLE
Use conda to install ruby 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#10]
For those who want to use conda to configure the ruby environment on Mac OS X:
```
conda install clangxx_osx-64 ruby make rb-jekyll
```
on Linux:
```
conda install gxx_impl_linux-64 ruby make rb-jekyll
```

There is some trouble with installing ruby packages via conda: 
```
Ignoring eventmachine-1.2.7 because its extensions are not built. Try: gem pristine eventmachine --version 1.2.7
Ignoring ffi-1.11.1 because its extensions are not built. Try: gem pristine ffi --version 1.11.1
Ignoring http_parser.rb-0.6.0 because its extensions are not built. Try: gem pristine http_parser.rb --version 0.6.0
Ignoring sassc-2.3.0 because its extensions are not built. Try: gem pristine sassc --version 2.3.0
```
I assume this is related to the pinning of the ruby version https://github.com/conda-forge/rb-eventmachine-feedstock/issues/3 but compiling locally worked fine for me. 

And for the Mac Users you might have to activate Xcode first:
```
xcode-select --install
xcodebuild -license
```

**Comment by ashtonmv** [comment]
This is nice- it didn't even occur to me to install ruby with conda. I'll add these instructions to the README
