### ISSUE TITLE
show pyiron.org as url

### ISSUE THREAD

**Issue by ashtonmv** [pyiron/pyiron.github.io#15]
I'm wondering if we can show "pyiron.org" in the browser url box, instead of "pyiron.github.io". I think it would look nicer, and we are paying good money for that domain name anyway.

This would require:
1. Adding "www.pyiron.org" as the custom domain under this repository's settings
2. Adding all 4 github page IP addresses as `A` records within our DNS settings (this lets us use "pyiron.org" along with "www.pyiron.org"):
```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

I don't have access to either settings or else I could do it myself. Usually it takes several minutes/ hours for these changes to propagate from the DNS to the live site, which unfortunately makes any troubleshooting quite annoying.

**Comment by jan-janssen** [comment]
We can ask Ulrich about this he is in control of the domain setup.

**Comment by jan-janssen** [comment]
The website is currently not reachable as Ulrich is configuring the pyiron.org domain.

**Comment by jan-janssen** [comment]
The transition worked - still the website is currently listed as "not secure" even though I set the mark for https. So I hope this is fixed within the next 24 hours, as it is stated on the GitHub documentation.

**Comment by ashtonmv** [comment]
Yeah it looks great! The https thing has also given me some grief in the past, so let's see if it's still misbehaving after a day or two.

**Comment by jan-janssen** [comment]
It is fixed now.
