### ISSUE TITLE
Alumni List

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#30]
@hickel said the list of Alumni looks kind of sad as it is all black. So he suggested we should color the names in blue.

**Comment by ashtonmv** [comment]
:laughing: I actually agree, it does look a bit like an obituary. But blue is the color for links on our site, so we should either make them clickable (then the question is what link/page should they direct to) or use some other color/styling.

**Comment by jan-janssen** [comment]
I am open for using another color - I am just not sure which one to choose.
