### ISSUE TITLE
Colors for affiliated projects 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#33]
For some affiliated projects there are no logos like - NGLview, phonopy, ... - so it might make sense to just have a circle with the name for those. In addition we should think about having a more unified design for the logos of the affiliated projects - maybe all in white, if that is possible.

**Comment by ashtonmv** [comment]
I think I more or less achieved this in #31. I guess there's no perfect solution for projects that have no logo, or that have strangely formatted logos, but what you suggested is probably the best solution.
