### ISSUE TITLE
UBC logo

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron.github.io#42]
I got the following message from my UBC contact:

> Hi Liam,
>
>I have read through the [branding guidelines](https://assets.brand.ubc.ca/downloads/ubc_brand_identity_rules.pdf) from UBC and also contacted the Branding and Marketing team regarding this. Their comment was to have the text included in the logo itself. 
>
>I am attaching how the logo should look like.
>
>Here is their message:
>
>Thanks for reaching out. The use of the UBC logo here appears to be correct, except the logo itself is wrong, and I've attached the correct crest. 
> 
>
>Thanks,
>
>Hari

The crest+text is attached, but it looks low-res to me and the aspect ratio won't work for us.
![ubc-logo-2018-fullsig-blue-rgb72](https://user-images.githubusercontent.com/20283329/92033443-f8392680-ed6b-11ea-9a71-001c6619b373.jpg)

It sounds like UBC wants the university name included with the text. For a better aspect ratio than the full signature, I suggest we use "Secondary Logo: Narrow Signature" available at [this page](https://brand.ubc.ca/guidelines/downloads/logos-signatures-and-visual-identity-assets/) and attached to this post.
![UBC-logo-2018-narrowsig-blue-rgb72](https://user-images.githubusercontent.com/20283329/92033684-5bc35400-ed6c-11ea-9ee7-74a0921bffb9.jpg)

I'm also attaching the straight-up crest downloaded from the same source in case the text really blows the aspect ratio. 
![UBC-logo-2018-crest-blue-rgb72](https://user-images.githubusercontent.com/20283329/92033793-8a412f00-ed6c-11ea-975d-1840db0aaa27.jpg)

To be honest I couldn't see what UBC was complaining about, but upon closer inspection I see that our font is different and the sun has a different number of rays. I hope I don't have to give my degree back as punishment for not noticing 😝 

No word yet on Leoben's signature.

**Comment by jan-janssen** [comment]
@ashtonmv addressed this in https://github.com/pyiron/pyiron.github.io/pull/41
