### ISSUE TITLE
Dark version of the pyiron logo

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#53]
@ashtonmv Can you also create a dark version of the pyiron logo which we can use for white backgrounds? For example I would like to change the icon of the GitHub organisation.

**Comment by ashtonmv** [comment]
Hi @jan-janssen, there is a dark logo under `images` that I probably failed to mention before. I removed a small mistake from it in the dark_logo branch I just merged.

**Comment by jan-janssen** [comment]
I updated the logos of the organisation - I guess it just takes a few minutes to go live.
