### ISSUE TITLE
Publications 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#58]
I went ahead and merged all the open pull requests. Now I noticed that it would be nicer to have the abstracts with full justification - @ashtonmv Can you change this?

**Comment by ashtonmv** [comment]
Sure, do you mean to center-justify the text of the abstract?

**Comment by jan-janssen** [comment]
I am sorry I am missing the english word, I mean the one on the top left: 
https://www.edgee.net/wp-content/uploads/2014/05/paragraph_alignments.png
