### ISSUE TITLE
Listing contributors 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#7]
Hi @ashtonmv 

Can you take a look at https://github.com/all-contributors/all-contributors ? It sounds like a nice automated way to add contributors to the website and I guess it would simplify the process of managing the contributors later on. 

Best, 

Jan

**Comment by ashtonmv** [comment]
Thanks @jan-janssen, I tried playing with that bot for a while today, and it seems like it is best suited to add contributors to the README, but would require some hacking to nicely format them anywhere else.

In #9 I implemented something similar but it uses ajax and jquery in the html page itself. I found that a little easier to customize, but if you prefer integrating with the bot I can try taking another swing at it.
