### ISSUE TITLE
News categories not found 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron.github.io#79]
It works locally for me but https://pyiron.org/category/releases/ returns a "not found" error.

**Comment by ashtonmv** [comment]
Good catch. The jekyll-archives plugin is apparently [not supported by Github Pages](https://github.com/github/pages-gem/pull/106), for reasons that I don't fully understand. I think I can manually fix it though.

**Comment by ashtonmv** [comment]
I probably accidentally reverted this at some point. Will open a new pr in a second.
