### ISSUE TITLE
Hosting beta versions of the website

### ISSUE THREAD

**Issue by ashtonmv** [pyiron/pyiron.github.io#83]
I have two fears and a suggestion:

- **Fear # 1:** the barrier for most group members exploring/testing new website features is still sufficiently high that I'm sure many don't want to go through the effort of setting up the local server, and understandably so.

- **Fear # 2:** there are a few hidden differences between the behavior of the local server and the github pages server that can create annoying, untestable errors when going live (see #71, #74, and #79).

- **Suggestion:** fork pyiron.github.io into a new repository "_beta_site" within our organization for host beta branches.

If we initialize _beta_site's github pages under its settings, its content will automatically be published online under pyiron.org/_beta_site. Then anyone developing a website feature could choose whatever branch they want to publish there, and would just have to sync its branches from the main repository via an occasional `git fetch upstream`. To alleviate my second fear while testing #82, I did this on [my own account](https://www.michael-ashton.com/pyiron_beta_site), but it's only a temporary solution because others cannot push to this fork.

**Comment by jan-janssen** [comment]
I like the idea, I am just wondering if it is not easier to just suggest people to fork this repository, rename it and submit their pull request from their personal fork. Then multiple users can each have one branch for development, if certain changes are not accepted the user can revert those easily by just removing his fork and creating a new one. I have the feeling that is simpler and cleaner compared to having multiple repositories on the pyiron account with the difficulty to keep those in sync.

**Comment by ashtonmv** [comment]
I agree that having people fork from the current setup is the cleanest strategy from a git standpoint. And actually I just learned about [mirroring a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository), which would automatically sync the beta repository to this main one at all times. In other words, after setting it up we would never have to touch "beta_site" except to choose its published branch. That's actually what I just changed my repository pyiron_beta_site to do. So if it keeps the pyiron organization cleaner, I am happy to just host beta previews on my page.

**Comment by jan-janssen** [comment]
Maybe I did not get it, is there anything specific about the setup of the repository? If I want to create my own fork for me to preview my changes that should work as well or?

**Comment by ashtonmv** [comment]
Yeah you can always preview your changes on your _local_ server, but what I want is to preview branches on a _github pages_ server - preferably somewhere "hidden" that outside users won't stumble upon - before merging them into the wild at pyiron.org. I no longer trust testing on only the local server, because it does not behave identically to the github server. This caused issues #71, #74, and #79 so far. Like I said, I'm perfectly happy to just preview/share my choice of branches under my mirror, https://github.com/ashtonmv/pyiron_beta_site. But if others want this control, they will either need to host their own mirrors on their own websites, or we could create a mirror within the pyiron organization that any of us could control.

**Comment by jan-janssen** [comment]
Just a quick reminder for me and others who want to try the beta site hosted on @ashtonmv account https://www.michael-ashton.com/pyiron_beta_site/
